name: Push cells

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build cells
      run: cd service/runtime/cells; bash build.sh
      env:
        USERNAME: ${{ secrets.GHCR_ACTOR }}
        PASSWORD: ${{ secrets.GHCR_PAT }}
        DOCKER_DOMAIN: ghcr.io
        IMAGE: micro/cells
